export const ActionTypes = {
    SET_ACCESS_TOKEN: 'SET_ACCESS_TOKEN',
    SET_USER: 'SET_USER',
    SET_FEATURED_PLAYLIST: 'SET_FEATURED_PLAYLIST',
    SET_RECENTLY_PLAYED: 'SET_RECENTLY_PLAYED',
    SET_SEARCH_RESULT: 'SET_SEARCH_RESULT',
    SET_CURRENT_TRACK: 'SET_CURRENT_TRACK',
}
